---
env:
  global:
    - WORKSPACE="/ci-actions/workspace"
    - HELM_VERSION="2.12.3"

stages:
  - helm-lint
  - test

jobs:
  include:
    - stage: helm-lint
      language: bash
      image: docker:18-git
      before_script:
        - docker pull smoloney/ci-actions-helm:${HELM_VERSION} > /dev/null
      script:
        - |
          docker run --rm -v ${PWD}:${WORKSPACE} \
          smoloney/ci-actions-helm:${HELM_VERSION} \
          --exec-args='helm lint ./test/ci-helm/pass'

    - stage: test
      language: bash
      image: docker:18-git
      script:
        - bash test.sh
