---
env:
  global:
    - WORKSPACE="/ci-actions/workspace"
    - HELM_VERSION="2.12.3"
    - PRETTIER_VERSION="1.16.4"

stages:
  - helm-lint
  - yaml-lint
  - test

jobs:
  include:
    - stage: helm-lint
      language: bash
      image: docker:18-git
      before_script:
        - docker pull smoloney/ci-actions-helm:${HELM_VERSION} > /dev/null
      script:
        - |
          docker run --rm -v "${PWD}:${WORKSPACE}" "smoloney/ci-actions-helm:${HELM_VERSION}" \
          --exec-args='helm lint ./test/ci-helm/pass'

    - stage: yaml-lint
      language: bash
      image: docker:18-git
      before_script:
        - docker pull smoloney/ci-actions-prettier:${PRETTIER_VERSION} > /dev/null
      script:
        - |
          docker run --rm -v "${PWD}:${WORKSPACE}" "smoloney/ci-actions-prettier:${PRETTIER_VERSION}" \
            --exclude='./test/ci-prettier/format' \
            --exclude='./test/ci-helm/pass/templates' \
            --exclude='./test/ci-helm/fail/templates' \
            --exclude='./test/ci-prettier/lint/ignore-fail.yaml' \
            --file-glob='*.y*ml' \
            --exec-args='prettier --check --parser yaml --config ./.prettierrc.yml'

    - stage: test
      language: bash
      image: docker:18-git
      script:
        - bash test.sh
