#!/bin/bash

set -eo pipefail

source ../common/functions.sh

WORKSPACE=/ci-actions/workspace
CURRENT_DIR=${DOCKERFILE_PATH%"/Dockerfile"}

cp ../common/*.sh ./

docker build \
  --build-arg WORKSPACE="${WORKSPACE}" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --no-cache \
  --force-rm \
  --tag "${DOCKER_REPO}":latest \
  ./

