#!/bin/bash

set -eo pipefail

source ../common/functions.sh

CURRENT_DIR=${DOCKERFILE_PATH%"/Dockerfile"}
CURRENT_REPO=${DOCKER_REPO#"index.docker.io/smoloney/ci-actions-"}
IMAGE="smoloney/ci-actions-${CURRENT_REPO}:latest"
RELATIVE_PATH="./"
BUNDLED_REPOS=(helm prettier remark)

if [[ ! -d /tmp/shunit2 ]]; then
  export current_dir
  current_dir="${PWD}"
  git clone -q https://github.com/kward/shunit2.git /tmp/shunit2 && \
  cd /tmp/shunit2 && \
  git checkout -q a35d3c && \
  cd "${current_dir}" || exit;
fi

for bundled_repo in "${BUNDLED_REPOS[@]}"; do
  bundled_repo_upper="$(uname -s | awk '{print toupper($0)}')"

  /tmp/shunit2/shunit2 \
    "${PWD%/*}/test/${bundled_repo}_tests.sh" \
    "${IMAGE}" \
    "${RELATIVE_PATH}" \
    "${PWD%/*}/test/ci-${bundled_repo}" \
    "$(cat ./Dockerfile  | sed -En "s/ARG ${bundled_repo_upper}_VERSION=\"//p" | sed -En 's/"//p')"
done

rm -rf /tmp/shunit2
