#!/bin/bash

set -eo pipefail

WORKSPACE=/ci-actions/workspace
CURRENT_DIR=${DOCKERFILE_PATH%"/Dockerfile"}

cp ../common/*.sh ./

if [[ "$(have_files_changed ${CURRENT_DIR})" == 'true' ]]; then
  docker build \
    --build-arg WORKSPACE="${WORKSPACE}" \
    --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --no-cache \
    --force-rm \
    --tag "${DOCKER_REPO}":latest \
    ./
else
  echo "No changes to the ${CURRENT_DIR} or ./common directories, build not required"
fi
